USE SPMEDICALGROUP_TARDE;
GO

--Criando Procedures
CREATE PROCEDURE INSERIR_DADOS_ESTATICOS
AS
BEGIN
	INSERT INTO TIPO_USUARIO(NOME)
		VALUES ('Administrador'),('Médico'),('Paciente')
	SELECT * FROM TIPO_USUARIO

	INSERT INTO TIPO_STATUS(NOME)
		VALUES('Confirmada'), ('Recusada'), ('Adiada'), ('Aguardando confirmação do médico'), ('Realizada'), ('Cancelada'), ('Agendada')
	SELECT * FROM TIPO_STATUS

	INSERT INTO CLINICA(NOME, RAZAO_SOCIAL, CNPJ, HORARIO_FUNCIONAMENTO,LOCALIDADE)
		VALUES ('SP Medical Group', 'SP MEDICAL GROUP', '12345678910111', 'Das 7hs às 19hs', 'Alameda Barão de Limeira, 539 - Santa Cecilia, São Paulo - SP, 01202-001')
END
GO

CREATE PROCEDURE INSERIR_ESPECIALIDADES
AS
BEGIN
	BULK INSERT ESPECIALIDADES
	FROM 'C:\SPMEDGROUP\Especialidades.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM ESPECIALIDADES
END
GO

CREATE PROCEDURE INSERIR_USUARIOS
AS
BEGIN
	BULK INSERT USUARIOS
	FROM 'C:\SPMEDGROUP\Usuários.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM USUARIOS
END
GO

CREATE PROCEDURE INSERIR_MEDICOS
AS
BEGIN
	BULK INSERT MEDICOS
	FROM 'C:\SPMEDGROUP\Médicos.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM MEDICOS
END
GO

CREATE PROCEDURE INSERIR_PACIENTES
AS
BEGIN
	BULK INSERT PACIENTES
	FROM 'C:\SPMEDGROUP\Pacientes.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM PACIENTES
END
GO

CREATE PROCEDURE INSERIR_CONSULTAS
AS
BEGIN
	BULK INSERT CONSULTAS
	FROM 'C:\SPMEDGROUP\Consultas.csv'
		WITH(
			FORMAT = 'csv',
			FIRSTROW = 2,
			FIELDTERMINATOR = ';',
			ROWTERMINATOR = '\n',
			CODEPAGE = 'ACP',
			DATAFILETYPE = 'Char'
		);
	SELECT * FROM CONSULTAS
END
GO

EXEC INSERIR_DADOS_ESTATICOS
EXEC INSERIR_ESPECIALIDADES
EXEC INSERIR_USUARIOS
EXEC INSERIR_MEDICOS
EXEC INSERIR_PACIENTES
EXEC INSERIR_CONSULTAS