USE SPMEDICALGROUP_TARDE;

--MÉDICOS
SELECT
	USUARIOS.NOME AS NOME_MÉDICO,
	USUARIOS.EMAIL,
	ESPECIALIDADES.NOME AS ESPECIALIDADE,
	MEDICOS.CRM
FROM
	MEDICOS
	INNER JOIN
	USUARIOS ON MEDICOS.ID_USUARIO = USUARIOS.ID
	INNER JOIN
	ESPECIALIDADES ON ESPECIALIDADES.ID = MEDICOS.ID_ESPECIALIDADE

--PACIENTES
SELECT
	USUARIOS.NOME AS PACIENTES,
	USUARIOS.EMAIL,
	USUARIOS.TELEFONE,
	PACIENTES.ENDERECO
FROM
	USUARIOS INNER JOIN PACIENTES
	ON PACIENTES.ID_USUARIO = USUARIOS.ID

--CONSULTAS
SELECT
	NOME_MEDICO.NOME AS NOME_DO_MEDICO,
	NOME_PACIENTE.NOME AS NOME_DO_PACIENTE,
	CONSULTAS.DATA_CONSULTA,
	CONSULTAS.OBSERVACOES,
	TIPO_STATUS.NOME AS STATUS_CONSULTA
FROM
	CONSULTAS
	INNER JOIN
	PACIENTES ON CONSULTAS.ID_PACIENTE = PACIENTES.ID
		INNER JOIN
		USUARIOS AS NOME_PACIENTE ON NOME_PACIENTE.ID = PACIENTES.ID_USUARIO
	INNER JOIN
	MEDICOS ON CONSULTAS.ID_MEDIO = MEDICOS.ID
		INNER JOIN
		USUARIOS AS NOME_MEDICO ON NOME_MEDICO.ID = MEDICOS.ID_USUARIO
	INNER JOIN
	TIPO_STATUS ON CONSULTAS.ID_STATUS = TIPO_STATUS.ID

--ESPECIALIDADES
SELECT * FROM ESPECIALIDADES

--STATUS
SELECT * FROM TIPO_STATUS

--TIPOS DE USUARIO
SELECT * FROM TIPO_USUARIO

--CLINICA
SELECT * FROM CLINICA