USE SPMEDICALGROUP_TARDE;

BULK INSERT ESPECIALIDADES
FROM 'C:\SPMEDGROUP\Especialidades.csv'
WITH(
	FORMAT = 'csv',
	FIRSTROW = 2,
	FIELDTERMINATOR = ';',
	ROWTERMINATOR = '\n',
	CODEPAGE = 'ACP',
	DATAFILETYPE = 'Char'
);

SELECT * FROM ESPECIALIDADES

CREATE PROCEDURE 